// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSuUBMeDZilB_DDWoyI0ggU5v0FvVAm3E',
    appId: '1:460729468355:web:06ffdee9748a2636dd6976',
    messagingSenderId: '460729468355',
    projectId: 'zeepalm-task',
    authDomain: 'zeepalm-task.firebaseapp.com',
    storageBucket: 'zeepalm-task.firebasestorage.app',
    measurementId: 'G-KRHM3JNPN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbkUwhiZpVy_NGMpbVh6a33oTpoOKNFI',
    appId: '1:460729468355:android:8a7aa7d17d7470ebdd6976',
    messagingSenderId: '460729468355',
    projectId: 'zeepalm-task',
    storageBucket: 'zeepalm-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7yMSGQFJb0CvZJXkDJT59ZIyRokgl4g',
    appId: '1:460729468355:ios:d1e16ccc7e6245dcdd6976',
    messagingSenderId: '460729468355',
    projectId: 'zeepalm-task',
    storageBucket: 'zeepalm-task.firebasestorage.app',
    iosBundleId: 'com.example.assesmentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7yMSGQFJb0CvZJXkDJT59ZIyRokgl4g',
    appId: '1:460729468355:ios:d1e16ccc7e6245dcdd6976',
    messagingSenderId: '460729468355',
    projectId: 'zeepalm-task',
    storageBucket: 'zeepalm-task.firebasestorage.app',
    iosBundleId: 'com.example.assesmentProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSuUBMeDZilB_DDWoyI0ggU5v0FvVAm3E',
    appId: '1:460729468355:web:a21f299bfc6a0336dd6976',
    messagingSenderId: '460729468355',
    projectId: 'zeepalm-task',
    authDomain: 'zeepalm-task.firebaseapp.com',
    storageBucket: 'zeepalm-task.firebasestorage.app',
    measurementId: 'G-R80SYQ6YR0',
  );
}
